### PR TITLE
Create container for deployment

### PR DESCRIPTION
**Pull request by tws4793**
To simplify the process of setting up, running and tearing down the application, we propose taking advantage of Docker containers.

### Added
- `Dockerfile` to specify build and setup steps
- `.dockerignore` file to ignore certain directories when running the COPY instructions set by the `Dockerfile`
- `docker-compose.yml` to set the parameters for running the container

### CODE REVIEW

**Comment by tws4793** [comment]
Inside `vue.config.js`, as the `Dockerfile` is set to build the package, please temporarily change the `publicPath` from the following:

```javascript
publicPath: process.env.NODE_ENV === 'production'
  ? '/vue-pure-pdpa/'
  : '/',
```

to

```javascript
publicPath: process.env.NODE_ENV === 'production'
  ? '/'
  : '/',
```

DO NOT COMMIT that file. We will fix `publicPath` separately so that it can handle different input depending on the deployment environment.

**Comment by tws4793** [comment]
Steps to change `publicPath` included in the README.

**Comment by tws4793** [comment]
For running the app in the container, just simply:

```shell
$ docker-compose up --build
```

Instead of the instructions in the README.

**Review by anka-213 — APPROVED** [review]

**Comment by anka-213** [comment]
Here's some info on .env files: https://docs.docker.com/compose/environment-variables/

Here's how to select between prod and dev: https://nodejs.dev/learn/nodejs-the-difference-between-development-and-production

**Pull request merged**
